config/routes.rb
# == Route Map
#
#                    Prefix Verb   URI Pattern                                                                              Controller#Action
#               cards_index GET    /cards/index(.:format)                                                                   cards#index
#              privacy_show GET    /privacy/show(.:format)                                                                  privacy#show
#              privacy_edit GET    /privacy/edit(.:format)                                                                  privacy#edit
#            privacy_update GET    /privacy/update(.:format)                                                                privacy#update
#                      root GET    /                                                                                        pages#index
#            privacy_policy GET    /privacy_policy(.:format)                                                                pages#privacy_policy
#                           GET    /auth/:provider/callback(.:format)                                                       sessions#create
#                   log_out GET    /log_out(.:format)                                                                       sessions#destroy
#            category_links GET    /category_links(.:format)                                                                pages#category_links
#                     users POST   /users(.:format)                                                                         users#create
#                 edit_user GET    /users/:id/edit(.:format)                                                                users#edit
#                      user GET    /users/:id(.:format)                                                                     users#show
#                           PATCH  /users/:id(.:format)                                                                     users#update
#                           PUT    /users/:id(.:format)                                                                     users#update
#                     links GET    /links(.:format)                                                                         links#index
#                           POST   /links(.:format)                                                                         links#create
#                      link DELETE /links/:id(.:format)                                                                     links#destroy
#    ynab_budget_categories GET    /ynab/budgets/:budget_id/categories(.:format)                                            ynab/categories#index
#      ynab_budget_accounts GET    /ynab/budgets/:budget_id/accounts(.:format)                                              ynab/accounts#index
#              ynab_budgets GET    /ynab/budgets(.:format)                                                                  ynab/budgets#index
#             privacy_cards GET    /privacy/cards(.:format)                                                                 privacy/cards#index
#      privacy_transactions POST   /privacy/transactions(.:format)                                                          privacy/transactions#receive
#        rails_service_blob GET    /rails/active_storage/blobs/:signed_id/*filename(.:format)                               active_storage/blobs#show
# rails_blob_representation GET    /rails/active_storage/representations/:signed_blob_id/:variation_key/*filename(.:format) active_storage/representations#show
#        rails_disk_service GET    /rails/active_storage/disk/:encoded_key/*filename(.:format)                              active_storage/disk#show
# update_rails_disk_service PUT    /rails/active_storage/disk/:encoded_token(.:format)                                      active_storage/disk#update
#      rails_direct_uploads POST   /rails/active_storage/direct_uploads(.:format)                                           active_storage/direct_uploads#create

Rails.application.routes.draw do
  get 'cards/index'
  get 'privacy/show'
  get 'privacy/edit'
  get 'privacy/update'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'pages#index'
  get '/privacy_policy' => 'pages#privacy_policy'
  get '/auth/:provider/callback' => 'sessions#create'
  get '/log_out' => 'sessions#destroy', as: :log_out
  get '/category_links' => 'pages#category_links', as: :category_links

  resources :users, only: %i[edit create show update]
  resources :links, only: %i[index create destroy]

  namespace :ynab do
    resources :budgets, only: [:index] do
      resources :categories, only: [:index]
      resources :accounts, only: [:index]
    end
  end

  namespace :privacy do
    resources :cards, only: [:index]
    post '/transactions' => 'transactions#receive', as: :transactions
  end
end

app/views/pages/category_links.html.erb
<ynab-privacy-ng>Loading...</ynab-privacy-ng>

app/views/pages/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm">
      <div class="jumbotron">
        <h4>YNAB</h4>
          <% if current_user %>
            <p>
             <span>Connected</span> <i class="material-icons">done</i>
            </p>
            <%= link_to "Log out from YNAB", log_out_path, class: 'btn btn-primary-indigo btn-lg' %>
          <% else %>
          <p>Log in with YNAB to START linking your transactions</p>
          <%= link_to "Sign in To YNAB", "/auth/ynab_auth", class: 'btn btn-primary-indigo btn-lg' %>
        <% end %>
        <br>
        <br>
        <br>
        <%= link_to "Privacy Policy", privacy_policy_path %>
      </div>
    </div>
    <div class="col-sm">
      <div class="jumbotron">
        <h4>Privacy.com</h4>
        <% if current_user %>

          <% if current_user.privacy_key.to_s.empty? %>
            <p>Add your Privacy.com Access token to receive transactions</p>
            <%= link_to 'Add Privacy Access Token', edit_user_path(current_user), class: 'btn btn-primary-indigo btn-lg'  %>
          <% else %>
            <p>
              <span>Connected</span> <i class="material-icons">done</i>
            </p>
            <%= link_to 'Edit Privacy Access Token', edit_user_path(current_user), class: 'btn btn-primary-indigo btn-lg'%>
          <% end %>


        <% else %>
          <p>Log in with YNAB first</p>
        <% end %>
      </div>
    </div>
  </div>
  <% if current_user && current_user.privacy_key %>
  <div class="row">
    <div class="mx-auto" style="margin-top: 100px">
      <%= link_to  'Create Card Links', category_links_path, class: 'btn btn-primary-indigo btn-lg' %>
    </div>
  </div>
  <% end %>
</div>

app/views/pages/privacy_policy.html.erb
<h3>Privacy Policy</h3>

<p>
  Data obtained through the YNAB API is only used to create Card Links and communicate with the YNAB API when a transaction from Privacy.com comes in.
</p>

<p>
  Data is stored in a database managed by Heroku which is backed up and encrypted by them. A user is required to authenticate with YNAB in order to use the application.
</p>

<p>
  This application does not store any personal or financial information.
</p>

<p>
  Data obtained through the application will not knowingly be shared with any third parties.
</p>

<p>
  This application will never ask for financial institution credentials.
</p>

<%= link_to 'Back to YNAB Privacy Linker :)', root_path, class: 'btn btn-primary-indigo btn-lg'  %>